config/routes.rb
Rails.application.routes.draw do
	default_url_options :host => "example.com"
	
  	devise_for :users
	resources :users, :controller => 'users'
  	
	resources :dashboard

	root to: "home#index"

	get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
	get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
	get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

	get "messages/inbox" => "message#inbox"
	get "messages/create/:to_id" => "message#create_get"
	post "messages/create/:to_id" => "message#create_post"

	#conversations
	resources :conversations do
		member do
			post :reply
			post :trash
			post :untrash
		end

	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_messageable

  def mailboxer_name
  	self.name
  end

  def mailboxer_email(object)
  	self.email
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  helper_method :mailbox, :conversation

  private

  def mailbox
  	@mailbox ||= current_user.mailbox
  end
  
  def conversation
    @conversation ||= mailbox.conversations.find(params[:id])
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:user_id, :name, :email, :password, :gym, :top_rope, :lead, :boulder)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:user_id, :email, :name, :description, :password, :current_password, :password_confirmation) }
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	before_action :authenticate_user!
	helper_method :mailbox, :conversation

	def index
		@conversations = current_user.mailbox.conversations
	end

	# def new
	# end

	def create
    	# @recipients = User.where(id: params['recipients'])
    	@body = params[:body]
    	@subject = params[:subject]
		@conversation = current_user.send_message(@recipients, conversation_params[:body], conversation_params[:subject]).conversation
		flash[:success] = "Your message was successfully sent!"
		redirect_to conversation_path(@conversation)
	end

	def show
		@conversation = current_user.mailbox.conversations.all

		@receipts = @conversation.order("created_at ASC")
    	@body = params[:body]
    	@subject = params[:subject]			
		# mark conversation as read
		# @conversation.mark_as_read(current_user)
	end

	def reply
		current_user.reply_to_conversation(@conversation, *message_params(:body, :subject))

		flash[:notice] = "Your reply message was successfully sent!"
		redirect_to conversation_path(@conversation)
	end

	def sent
		current_user.mailbox.sentbox
	end


	def trash
		@conversation = current_user.mailbox.conversations.find_by(id: params[:id])
		@conversation.destroy

		# @conversation = current_user.send_message(@recipients, conversation_params[:body], conversation_params[:subject]).conversation
		if @conversation
			flash[:success] = 'The conversation was moved to trash.'
			redirect_to mailbox_inbox_path
		end
	end

	def untrash
		@conversation.untrash(current_user)
		redirect_to mailbox_inbox_path
	end

	def empty_trash
		current_user.mailbox.trash.each do |conversation|
			conversation.receipts_for(current_user).update_all(:deleted == true)
		end
		redirect_to :conversations
	end


	private

	def mailbox
 		@mailbox ||= current_user.mailbox
	end

	def conversation_params
		params.require(:conversation).permit(:subject, :body)
	end


	def conversation
        @conversation ||= mailbox.conversations.all(params[:id])
	end

	def message_params(*keys)
		params.require(:message).permit(:body, :subject)
	end

	
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_filter :authenticate_user!
	
	def index
		@users = User.all
		@user = current_user
	end

	# def new
	# 	@user = User.new
	# 	p @user
	# end

	# def edit
	# 	user_id = params[:id]
	# 	@user = User.find_by_id(user_id)
	# end

	# def create 
	# 	@user = User.create(user_params)
	# 	login(@user)
	# 	p @user
	# 	if user.save
	# 		redirect_to user_registration_path
	# 	end
	# end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to user_registration_path
		end
	end
	
	private 

	def user_params
		params.require(:user).permit(:user_id, :name, :email, :password, :gym, :top_rope, :lead, :boulder)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController


	def index 
		if user_signed_in?
			redirect_to :controller=>'dashboard', :action => 'index'
		end
	end


end

app/controllers/mailbox_controller.rb
class MailboxController < ApplicationController
	before_action :authenticate_user!

	def inbox
		@inbox = mailbox.inbox
		@active = :inbox
	end

	def sent 
		@sent = mailbox.sentbox
		@active = :sent
	end

	def trash 
		@trash = mailbox.trash
		@active = :trash
	end

end

app/controllers/message_controller.rb
class MessageController < ApplicationController
	before_action :authenticate_user!

	def inbox
		# find all message where: Message.to == current_user.id || Message.from == current_user.id
		# - now you have all the messages that involve a user (both sent and received) 
	end

	def create_get
		# get all the other friends/users, make them available to your page
	end

	def create_post
		# data POSTed up: to (id), message
		# data.from = current_user.id
		# data.createdAt = now()
		# MessagesTable.create(data) // inserts new record into Messages Table in database
	end

	def trash 
		# todo later
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
		
	end

	# def create 
	# 	@user = User.create(user_params)
	# 	login(@user)
	# 	if @user.save
	# 		redirect_to @user
	# 	end
		
	# end

	def show 
		user_id = params[:id]
		@user = User.find_by_id(user_id)
	end

	def edit
		user_id = params[:id]
		@user = User.find_by_id(user_id)
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to user_registration_path
		end
	end

	private 

	def user_params
		params.require(:user).permit(:user_id, :name, :email, :password, :gym, :top_rope)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def flash_class(level)
		case level.to_sym
			when :notice then "alert alert-success"
			when :info then "alert alert-info"
			when :alert then "alert alert-danger"
			when :warning then "alert alert-warning"
		end
	end
	
	def resource_name
		:user
	end

	def resource
		@user ||= User.new(params[:id])
	end

	def devise_mapping
		@devise_mapping ||= Devise.mappings[:user]
	end

	def active_page(active_page)
		@active == active_page ? "active" : ""
	end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mailbox_helper.rb
module MailboxHelper

	def unread_messages_count
		# how to get the number of unread messages for the current user
		# using mailboxer
		mailbox.inbox(:unread => true).count(:id, :distinct => true)
	end
	
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/conversations/_conversation.html.erb
<div class="row" id="nav_links">
<div class="col-md-8">
<div class="media">
  <div class="media-left">
    <a href="#">
      <img class="media-object" src="http://placehold.it/64x64" alt="...">
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading">
      <%= conversation.originator.name %> <br>
      <small><b>Subject: </b><%= conversation.subject %></small><br>
      <small><b>Date: </b><%=  conversation.messages.last.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
    </h4>
    <%= truncate conversation.messages.last.body, length: 145 %>
    <%= link_to "View", conversation_path(conversation)  %>
  </div>
</div>
<div class="row">
  <div class="spacer"></div>
  <div class="col-md-6">
    <%= link_to "Compose", new_conversation_path, class: "btn btn-success" %>
  </div>
  <div class="col-md-6 text-right">
    <% if conversation.is_trashed?(current_user) %>
        <%= link_to 'Untrash', untrash_conversation_path(conversation), class: 'btn btn-info', method: :post %>
    <% else %>
        <%= link_to 'Move to trash', trash_conversation_path(conversation), class: 'btn btn-danger', method: :post,
                    data: {confirm: 'Are you sure?'} %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="spacer"></div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render partial: 'messages' %>
      </div>
      <div class="panel-footer">
        <!-- Reply Form -->
        <%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
            <div class="form-group">
              <%= f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control" %>
            </div>
            <%= f.submit "Reply", class: 'btn btn-danger pull-right' %>
        <% end %>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>

</div>

app/views/conversations/_form.html.erb
<%= form_for :conversation, url: :conversations, html: { class: "", :id => "conversation_form" } do |f|%>
    <div class="form-group">
      <%= f.label :recipients %>
      <%= f.select(:recipients, User.all.collect {|p| [ p.name, p.id ] }, {}, { multiple: true , class: "chosen-select form-control" })%>
    </div>
    <div class="form-group">
      <%= f.label :subject %>
      <%= f.text_field :subject, placeholder: "Subject", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :message %>
      <%= f.text_area :body, class: 'form-control',placeholder: "Type your message here", rows: 4  %>
    </div>

    <%= f.submit "Send Message", class: "btn btn-success" %>

<% end %>

app/views/conversations/_messages.html.erb
<% @receipts.each do |receipt| %>
    <div class="media">
      <div class="media-left">
        <!-- user avators can go here -->

      </div>
      <div class="media-body">
        <h4 class="media-heading">

          <%= receipt.subject %> <br>
          <% @message_id = receipt.id %>

          <%= link_to ' ', trash_conversation_path(@message_id), class: "glyphicon glyphicon-trash", :method => :post, data: {confirm: 'Are you sure?'} %>

      <div class="col-md-8">
          <small><b>Subject: </b><%= receipt.subject %></small><br>
      </div>
       </h4>

      </div>
    </div>
<% end %>

app/views/conversations/index.html.erb
<h1>All Conversations</h1>

<% @conversations.each do |conversation| %>
	<div>
	<% link_to conversation.subject %>

<% end %>

app/views/conversations/new.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: true } %>

app/views/conversations/show.html.erb
<div class="row" id="nav_links">
<div class="col-md-12">
<h1 id="quote">"It's not about the destination,it's about the journey and what it took to get you there!"</h1>
</div>
  <div class="col-md-2">
      <%= image_tag "climb19.png", :class => "image_15" %>
  </div>
  <div class="col-md-4" id="entire_conversation">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render partial: 'messages' %>
      </div>
      <div class="panel-footer">
        <!-- Reply Form -->
        <div class="form-group">
        <%= link_to "Compose", new_conversation_path, class: "btn btn-success pull-right" %>
        </div>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>
    <div class="col-md-2">
      <%= image_tag "climb13.png", :class => "image_13" %>
    </div>
</div>
<div class="row" id="nav_links">
  <div class="col-md-2">
      <%= image_tag "climb2.png", :class => "image_17" %>
  </div>
  <div class="col-md-4">
  </div>

    <div class="col-md-2">
      <%= image_tag "climb15.png", :class => "image_16" %>
    </div>
</div>

app/views/dashboard/index.html.erb
<div class="container">
	<div class="row" id="nav_links">
	<div class="row" id="row1">
		<div class="col-md-3">
			<%= image_tag "climb10.png", :class => "image_1" %>
		</div>
		<div class="col-md-3">
			<%= image_tag "climb12.png", :class => "image_2" %>
		</div>
		<div class="col-md-3">
			<%= image_tag "climb14.png", :class => "image_3" %>
		</div>
		<div class="col-md-3">
			<%= image_tag "climb9.png", :class => "image_4" %>
		</div>
	</div>

	<div class="row" id="community_row">
		<h1 id="community_title">Find your new climbing buddy!</h1>
		<br/>
			<% @users.each do |user| %>
			<div class="col-md-3">
			<%= image_tag "climb11.png", :class => "image img-circle" %>
				<br/>
		        <%= link_to user.name, user_path(user), :id => "user_name"%>
		        <br/>
		        <h5 class="attribute"><%= user.gym %></h5>
		        <h5 class="attribute">Top Rope: <%= user.top_rope %></h5>
		        <h5 class="attribute">Lead: <%= user.lead %></h5>
		        <h5 class="attribute">Boulder: <%= user.boulder %></h5>
				<%= link_to "Message", new_conversation_path, :class => "message" %>
				<br/>
			</div>
		<% end %>
	</div>
</div>

app/views/dashboard/show.html.erb
<div class="container">
	<div class="row">
			<h1>Welcome <%= user.name %></h1>
        <img id="profile-photo" class="circle responsive-img" src="http://placehold.it/250x250">
	</div>
</div>

<div class="container">
    <%= link_to "Edit Profile", edit_user_registration_path, :method => :get, class: "btn btn-default"%>
</div>
<%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
  <h2>Which gym do you climb at?</h2>
  <hr/>
  <div class="row">
  <div class="col-lg-4">
    <div class="field">
        <%= f.radio_button(:gym, "gym1") %>
        <%= f.label(:gym, "Planet Granite"), :value => "planet granite" %>
      <br/>
    </div>
    <div class="field">
        <%= f.radio_button(:gym, "gym2") %>
        <%= f.label(:gym, "Mission Cliffs"), :value => "mission cliffs" %>
      <br/>
    </div>
    <div class="field">
        <%= f.radio_button(:gym, "gym3") %>
        <%= f.label(:gym, "Dogpatch"), :value => "dogpatch" %>
    </div>
  </div>
  </div>
  <div class="row">
    <div class="col-lg-4">
    <h2>Choose Your Skill Level Right Now</h2>
    <hr/>

    <div class="row">
      <div class="col-lg-4">
        <h3>Top Rope</h3>
          <select id="slct1" class="browser-default" onchange="populate(this.id, '">
            <option value="" disabled selected>Choose your option</option>
            <option value="1">5.8</option>
            <option value="2">5.9</option>
            <option value="3">5.10a</option>
            <option value="3">5.10b</option>
            <option value="3">5.10c</option>
            <option value="3">5.10d</option>
            <option value="3">5.11a</option>
            <option value="3">5.11b</option>
            <option value="3">5.11c</option>
            <option value="3">5.11d</option>
          </select>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4">
        <h3>Lead</h3>
          <select id="slct1" class="browser-default" onchange="populate(this.id, '">
            <option value="" disabled selected>Choose your option</option>
            <option value="1">5.8</option>
            <option value="2">5.9</option>
            <option value="3">5.10a</option>
            <option value="3">5.10b</option>
            <option value="3">5.10c</option>
            <option value="3">5.10d</option>
            <option value="3">5.11a</option>
            <option value="3">5.11b</option>
            <option value="3">5.11c</option>
            <option value="3">5.11d</option>
          </select>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4">
        <h3>Boulder</h3>
          <select class="browser-default">
            <option value="" disabled selected>Choose your option</option>
            <option value="1">v0</option>
            <option value="2">v1</option>
            <option value="3">v2</option>
            <option value="3">v3</option>
            <option value="3">v4</option>
            <option value="3">v5</option>
            <option value="3">v6</option>
            <option value="3">v7</option>
            <option value="3">v8</option>
            <option value="3">v9</option>
          </select>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/home/index.html.erb
<div class="container">
	<div class="row" id="row1">
		<div class="col-md-3">
			<%= image_tag "climb1.png", :class => "image_1" %>
		</div>
		<div class="col-md-3">
			<%= image_tag "climb2.png", :class => "image_2" %>
		</div>
		<div class="col-md-3">
			<%= image_tag "climb3.png", :class => "image_3" %>
		</div>
		<div class="col-md-3">
			<%= image_tag "climb4.png", :class => "image_4" %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-3">
			<%= image_tag "climb5.png", :class => "image_5" %>
		</div>
		<div class="col-md-5">
			<h3 id="title">Climb With Me</h3>
			<h5 id="tag_line">Meet your new climbing buddy!</h5>
		</div>
		<div class="col-md-3">
			<%= image_tag "climb6.png", :class => "image_6" %>
		</div>
	</div>
	<div class="row" id="row1">
		<div class="col-md-3">
			<%= image_tag "climb7.png", :class => "image_7" %>
		</div>
		<div class="col-md-3">
			<%= image_tag "climb8.png", :class => "image_8" %>
		</div>
		<div class="col-md-3">
			<%= image_tag "climb9.png", :class => "image_9" %>
		</div>
		<div class="col-md-3">
			<%= image_tag "climb10.png", :class => "image_25" %>
		</div>
	</div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Messenger", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
            <li><%= link_to "Hello, #{current_user.name}", "#" %></li>
            <li><%= link_to "Inbox", mailbox_inbox_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li class="active"><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Climb With Me</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>

  <body>
    <ul class="nav navbar-nav pull-left">
      <% if user_signed_in? %>
      <% end %>
    </ul>
    <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
          <%= link_to "Profile", edit_user_registration_path, :method => :get, class: "btn btn-default submit"%>

          <%= link_to "Community", dashboard_index_path, :method => :get, class: "btn btn-default nav_link submit"%>
          <%= link_to "Inbox", conversation_path(:user), :method => :get, class: "btn btn-default nav_link submit"%>
          <%= link_to "Log out", destroy_user_session_path, :method => :delete, class: "btn btn-default nav_link submit" %>
        <% else %>
            <%= form_for(:user, :url => session_path(:user), html: { class: "navbar-form navbar-right form-inline" }) do |f| %>
                    <div class="form-group">
                      <%= f.text_field :email, :placeholder => "Email", class: "form-control submit" %> 
                    </div>
                    <div class="form-group">
                      <%= f.password_field :password, :placeholder => "Password", class: "form-control submit"  %>
                    </div>
                    <%= f.submit 'Login', class: "btn btn-default submit" %>
                    <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-default submit" %> 
            <% end %>
        <% end %>
      </ul>

  <%= yield %>

    <% flash.each do |key, value| %>
    <% end %>

  </body>
</html>

app/views/mailbox/_folder_view.html.erb
<div class="row" id="nav_links">
  <div class="spacer"></div>
  <div class="col-md-12">
    <div class="spacer"></div>
  </div>
    <div class="col-md-2">
      <%= image_tag "climb12.png", :class => "image_6" %>
    </div>
    <div class="col-md-8">
        <% if is_conversation %>
            <%= render 'conversations/form' %>
        <% else %>
            <%= render partial: 'conversations/conversation', collection: messages %>
        <% end %>
    </div>
</div>
    <div class="col-md-2">
      <%= image_tag "climb15.png", :class => "image_10" %>
    </div>

app/views/mailbox/_folders.html.erb
<ul class="nav nav-pills nav-stacked">
  <li class="<%= active_page(:inbox) %>">
    <%= link_to mailbox_inbox_path do  %>
       <em class="fa fa-inbox fa-lg"></em>
        <span>Inbox</span>
    <% end %>
  </li>
  <li class="<%= active_page(:sent) %>">
    <%= link_to mailbox_sent_path do %>

        <em class="fa fa-paper-plane-o fa-lg"></em>
        <span>Sent</span>
    <% end %>
  </li>

  <li class="<%= active_page(:trash) %>">
    <%= link_to mailbox_trash_path do %>
        <em class="fa fa-trash-o fa-lg"></em>
        <span>Trash</span>
    <% end %>
  </li>
</ul>

app/views/mailbox/_messages.html.erb
<div class="row" id="nav_links">
  <div class="col-md-6">

<% @conversations.each do |message| %>
    <div class="media">
      <div class="media-left">
        <!-- user avators can go here -->
        <a href="#">
          <img class="media-object" src="http://placehold.it/64x64" alt="...">
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading">
          <%= message.subject %> <br>
          <small><b>Subject: </b><%= message.subject %></small><br>
        </h4>

      </div>
    </div>
<% end %>
</div>
</div>

app/views/mailbox/inbox.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @inbox } %>

app/views/mailbox/sent.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @sent } %>

app/views/mailbox/trash.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @trash } %>

app/views/users/shared/_links.html.erb
<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<div class="row" id="nav_links">
	<div class="col-md-12">
		<center><h1 class="user_profile_name"><%= @user.name %></h1></center>
		<div class="col-md-5">
	    <%= image_tag(@user.image, :height => 400, :width => 400) %> 
	    </div>
	    <br/>
	    <h3 class="gym">I climb at <%= @user.gym %></h3>
	    <h3 class="gym">When I climb at the gym I mostly, </h3>
	    <h3 class="gym">top rope: <%= @user.top_rope %></h3>
	    <h3 class="gym">lead: <%= @user.lead %></h3>
	    <h3 class="gym">boulder: <%= @user.boulder %></h3>
		<%= link_to "Message", new_conversation_path, :class => "message" %>
    </div>
</div>
<%= link_to "Back", :back, :class => "submit" %>